doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '12.2'
        charset: utf8
        default_table_options:
            charset: utf8

        url: '%env(resolve:DATABASE_URL)%'

        types:
            user_user_email: 'App\Domain\User\Entity\EmailType'
            user_user_phone: 'App\Domain\User\Entity\PhoneType'
            user_user_role: 'App\Domain\User\Entity\RoleType'
            user_user_status: 'App\Domain\User\Entity\StatusType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/User/Entity'
                prefix: 'App\Domain\User\Entity'
                alias: User
            Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Product/Entity'
                prefix: 'App\Domain\Product\Entity'
                alias: Product
