knp_paginator:
  default_options:
    sort_field_name:      sort
    sort_direction_name:  direction
    filter_field_name:    filterField
    filter_value_name:    filterValue
    page_name:            page
    distinct:             true
  template:
    pagination:           '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
    filtration:           '@KnpPaginator/Pagination/filtration.html.twig'
    sortable:             '@KnpPaginator/Pagination/twitter_bootstrap_v4_font_awesome_sortable_link.html.twig'
  page_range:           5
  page_limit:           100